=== jmperez321/Lenguage-de-Marcas/DTD/RA4_PT2_EJ2_DTD.dtd
<!ELEMENT arrel (c:esdeveniments+, t:esdeveniments+)><!--Esta linea declara el element root con esdeveniment+ ya que puede haber 1 o mas-->
<!ATTLIST arrel xmlns CDATA "http://www.elpuig.xeill.net/default">
<!ATTLIST arrel xmlns:c CDATA "http://www.elpuig.xeill.net/concerts">
<!ATTLIST arrel xmlns:t CDATA "http://www.elpuig.xeill.net/teatre">
<!ELEMENT c:esdeveniments (c:esdeveniment+)><!--Esta linea declara el element root con esdeveniment+ ya que puede haber 1 o mas-->
<!ELEMENT c:esdeveniment (c:grup, c:lloc, c:data, c:entrada)> <!--Esta linea declara el elementGroup esdeveniment y sus elementos-->
<!ELEMENT c:grup (#PCDATA)>
<!ELEMENT c:lloc (#PCDATA)>
<!ELEMENT c:data (#PCDATA)>
<!ELEMENT c:entrada (#PCDATA)>
<!--las lineas anteriores son los campos-elementos que contiene el c:grupo los cuales se les puede introducir texto-->
<!ATTLIST c:entrada gratuita ( si | no ) #REQUIRED>
<!--Define el atributo "gratuita" de entrada la cual puede ser boleana e indicar su valor o no -->

<!ELEMENT t:esdeveniments (t:esdeveniment+)><!--Esta linea declara el element root con esdeveniment+ ya que puede haber 1 o mas-->
<!ELEMENT t:esdeveniment (t:companyia, t:lloc, t:data, t:entrada)> <!--Esta linea declara el elementGroup esdeveniment y sus elementos-->
<!ELEMENT t:companyia (#PCDATA)>
<!ELEMENT t:lloc (#PCDATA)>
<!ELEMENT t:data (#PCDATA)>
<!ELEMENT t:entrada (#PCDATA)>
<!--las lineas anteriores son los campos-elementos que contiene el c:grupo los cuales se les puede introducir texto-->

=== jmperez321/Lenguage-de-Marcas/DTD/Exemple2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE arrel SYSTEM "RA4_PT2_EJ2_DTD.dtd">

<arrel xmlns="http://www.elpuig.xeill.net/default" 
    xmlns:c="http://www.elpuig.xeill.net/concerts" 
    xmlns:t="http://www.elpuig.xeill.net/teatre">
	<c:esdeveniments>
		<c:esdeveniment>
			<c:grup>Oques Grasses</c:grup>
			<c:lloc>El moll de la fusta</c:lloc>
			<c:data>2017-09-12 22:30</c:data>
			<c:entrada gratuita="si"/>
		</c:esdeveniment>
		<c:esdeveniment>
			<c:grup>Zoo</c:grup>
			<c:lloc>Sala Apolo</c:lloc>
			<c:data>2018-01-03 02:45</c:data>
			<c:entrada gratuita="no">25</c:entrada>
		</c:esdeveniment>
		<c:esdeveniment>
			<c:grup>Txarango</c:grup>
			<c:lloc>El Poble Espanyol</c:lloc>
			<c:data>2018-06-24</c:data>
			<c:entrada gratuita="no">17.5</c:entrada>
		</c:esdeveniment>
	</c:esdeveniments>

	<t:esdeveniments>
		<t:esdeveniment>
			<t:companyia>La Cubana</t:companyia>
			<t:lloc>Teatre Colisseum</t:lloc>
			<t:data>2017-11-26 20:30</t:data>
			<t:entrada>Lliure</t:entrada>
		</t:esdeveniment>
		<t:esdeveniment>
			<t:companyia>El Tricicle</t:companyia>
			<t:lloc>Teatre Poliorama</t:lloc>
			<t:data>2018-12-01 21:00</t:data>
			<t:entrada>22€ per a majors de 18 anys; 5€ per a menors de 18 anys i majors de 65 anys.</t:entrada>
		</t:esdeveniment>	
	</t:esdeveniments>
</arrel>
